language: php

php:
- 7.1
- 7.2

env:
    matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
- mysql -e 'CREATE DATABASE test_om;'

script:
- vendor/bin/phpunit --coverage-html --coverage-clover=coverage.clover --configuration phpunit.xml.travis

services:
- mysql

after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
